---

tenants:
  PACKETANGLERS:
    mac_vrf_vni_base: 10000
    evpn_l2_multi_domain: false
    vrfs:
      CORP:
        vrf_vni: 50001
        mlag_ibgp_peering_vlan: 4001
        mlag_ibgp_peering_ipv4_pool: 192.2.2.0/24
        svis:
          10:
            name: Ten
            description: App Servers
            tags: ['APP']
            enabled: true
            mtu: 9014
            ip_address_virtual: 10.10.10.1/24
            evpn_l2_multi_domain: true
          20:
            name: Twenty
            description: Web Servers
            tags: ['WEB']
            enabled: true
            mtu: 9014
            ip_address_virtual: 10.20.20.1/24
            evpn_l2_multi_domain: true
          30:
            name: Thirty
            description: DB Servers
            tags: ['DB']
            enabled: true
            mtu: 9014
            ip_address_virtual: 10.30.30.1/24

    l2vlans:
      40:
        name: Forty
        tags: ['CUST-A']
      50:
        name: Fifty
        tags: ['CUST-B']